RaltsPicFront::    INCBIN "pic/bmon/ralts.pic"
RaltsPicBack::     INCBIN "pic/monback/raltsb.pic"
KirliaPicFront::   INCBIN "pic/bmon/kirlia.pic"
KirliaPicBack::    INCBIN "pic/monback/kirliab.pic"
GardevoirPicFront::INCBIN "pic/bmon/gardevoir.pic"
GardevoirPicBack:: INCBIN "pic/monback/gardevoirb.pic"
BagonPicFront::    INCBIN "pic/bmon/bagon.pic"
BagonPicBack::     INCBIN "pic/monback/bagonb.pic"
ShelgonPicFront::  INCBIN "pic/bmon/shelgon.pic"
ShelgonPicBack::   INCBIN "pic/monback/shelgonb.pic"
SalamencePicFront::INCBIN "pic/bmon/salamence.pic"
SalamencePicBack:: INCBIN "pic/monback/salamenceb.pic"